- name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy pandas yfinance mplfinance requests
          pip install pandas-ta==0.3.14b0 --no-deps
